name: selenium-github-actions
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: set-env
        env:
          URL: ${{secrets.URL}}
          ID: ${{secrets.ID}}
          PASSWORD: ${{secrets.PASSWORD}}
          ID_XPATH: ${{secrets.ID_XPATH}}
          PASS_XPATH: ${{secrets.PASS_XPATH}}
          LOGIN_XPATH: ${{secrets.LOGIN_XPATH}}
          LINE_NOTIFY_TOKEN: ${{secrets.LINE_NOTIFY_TOKEN}}
          CALENDAR_XPATH: ${{secrets.CALENDAR_XPATH}}
          WORD_1: ${{secrets.WORD_1}}
          WORD_2: ${{secrets.WORD_2}}
          WORD_3: ${{secrets.WORD_3}}
          TEXT1: ${{secrets.TEXT1}}
          TEXT2: ${{secrets.TEXT2}}
          TEXT3: ${{secrets.TEXT3}}
        run: echo "Environment variables set"
      - run: |
          pip install get-chrome-driver --upgrade
          pip install -r requirements.txt
          python3 main.py
